# .github/workflows/main.yml
name: GreenPrint CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        
    - name: Backend Tests
      run: |
        cd backend
        npm install
        npm test
        
    - name: Frontend Tests
      run: |
        cd frontend
        npm install
        npm test
        
  build:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Build and push Frontend
      uses: docker/build-push-action@v2
      with:
        context: .
        file: infra/docker/frontend.Dockerfile
        push: true
        tags: yourdockerhub/greenprint-frontend:latest
        
    - name: Build and push Backend
      uses: docker/build-push-action@v2
      with:
        context: .
        file: infra/docker/backend.Dockerfile
        push: true
        tags: yourdockerhub/greenprint-backend:latest